=== lixu1/JavaScript/111_dogs.dtd
<!--The myDogs DTD-->
<!ELEMENT myDogs (dog+)>

<!--The <dog/> section-->
<!ELEMENT dog(name,age,fullBlood,color)>
<!ATTLIST dog breed CDATA #REQUIRED>
<!ELEMENT name(#PCDATA)>
<!ELEMENT age(years,months)>
	<!--The <age/>section-->
	<!ELEMENT months(#PCDATA)>
	<!ELEMENT years(#PCDATA)>
	<!--END age section-->
<!ELEMENT fullBlood (#PCDATA)>
<!ELEMENT color(#PCDATA)>
<!--END <dog/>section-->
<!--END of myDogs DTD-->

=== lixu1/JavaScript/112_dogs.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<?xml-stylesheet type="text/xsl" href="114_dogs.xsl"?>

<!--?xml-stylesheet href="113_dogs.css" type="text/css"?-->

<!DOCTYPE myDogs SYSTEM "111_dogs.dtd">

<myDogs>
<dog breed="Labrabor Retriever">
<name>Morgan</name>
<age>
<years>0</years>
<months>10</months>
</age>
<fullBlood>yes</fullBlood>
<color>chocolate</color>
</dog>
<dog breed="Labrador Retriever">
<name>Molly</name>
<age><years>8</years>
<months>11</months>
</age>
<fullBlood>yes</fullBlood>
<color>yellow</color>
</dog>
<dog breed="Pomeranian">
<name>Casey</name>
<age>
<years>6</years>
<months>2</months>
</age>
<fullBlood>yes</fullBlood>
<color>brown</color>
</dog>
</myDogs>
